FROM ppllondonintacrixygq5.azurecr.io/ppl-london-int-w4tzq2:v14

WORKDIR /app

COPY .streamlit ./.streamlit
COPY app.py ./
COPY project_paths.py ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY docs ./docs
COPY scripts ./scripts
COPY webapp ./webapp
COPY data/cache ./data/cache
