FROM ppllondonintacrixygq5.azurecr.io/ppl-london-int-w4tzq2:v11

WORKDIR /app

COPY .streamlit ./.streamlit
COPY app.py ./
COPY project_paths.py ./
COPY requirements.txt ./
COPY docs ./docs
COPY scripts ./scripts
COPY data ./data
COPY webapp ./webapp
